name: K6 Test Maskinporten

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment: either systest (maskinporten.dev) or test (test.maskinporten.no)'
        required: true
        type: choice
        options:
          - "https://maskinporten.dev"
          - "https://test.maskinporten.no"
          - "https://test1.maskinporten.no"
          - "https://ver2.maskinporten.no"
      test-type:
        description: 'Load test config to run: stress-test.json | stress-test-breakpoint.json | normal-load.json | normal-30min-load.json | normal-15min-load.json | normal-5min-load.json | normal-1s-load.json | stabilitet-test.json | stabilitet-test-200.json'
        required: true
        default: 'normal-load.json'
      clients-file:
        description: 'Clients file as JSON. Default ./clients-ver2.json'
        required: true
        type: choice
        options:
          - "./clients-ver2.json"
          - "./buggy-clients-ver2.json"
    
