name: Trigger Action on a CRON Schedule
      
on:
  schedule:
    - cron: '1/3 * * * *'
  workflow_call:
    inputs:
      logLevel:
        required: true
        type: string

jobs:
  test:
    uses: ./.github/workflows/run-job-with-params.yml
    secrets: inherit
    with:
      springProfile: 'production'
      logLevel: ${{ inputs.logLevel || 'DEBUG' }}
