

name: WebDriverIO Automation

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      envPAT:
        required: true
  schedule:
           - cron: "*/3 * * * *"  
    
jobs:
  test:
    uses: ./.github/workflows/run-job-with-params.yml
    secrets: inherit
    with:
      springProfile: 'production'
      logLevel: ${{ inputs.logLevel || 'DEBUG' }}    
